### ISSUE TITLE
Apply a license

### ISSUE THREAD

**Issue by FlorentPoinsaut** [particuleio/terraform-scaleway-kapsule#13]
Hello,

Thank you for this great module!
Please, could you apply a free/libre and open-source software license to your code?
May I suggest you add the LICENSE GPLv3 (https://www.gnu.org/licenses/quick-guide-gplv3.html)?

Help by GitHub : https://help.github.com/en/articles/adding-a-license-to-a-repository

Thank you in advance. 🙏

Regards,

**Comment by ArchiFleKs** [comment]
Done
