### ISSUE TITLE
experiments is no longer support in terraform v1.3.1

### ISSUE THREAD

**Issue by Xaving** [particuleio/terraform-scaleway-kapsule#23]
In version.tf,
https://github.com/particuleio/terraform-scaleway-kapsule/blob/8d064e441b95c572c0f6fb33101e17ff5981061c/versions.tf#L3
the experiments attribute throws the following  error with terraform 1.3.1.

```
╷
│ Error: Experiment has concluded
│ 
│   on .terraform/modules/..../versions.tf line 3, in terraform:
│    3:   experiments = [module_variable_optional_attrs]
│ 
│ Experiment "module_variable_optional_attrs" is no longer available. The final feature corresponding to this experiment differs from the experimental
│ form and is available in the Terraform language from Terraform v1.3.0 onwards.
╵
```
a related link [here](https://github.com/hashicorp/terraform/issues/31692).

**Comment by ArchiFleKs** [comment]
Fixed in https://github.com/particuleio/terraform-scaleway-kapsule/releases/tag/v6.0.0
