### ISSUE TITLE
feat: add missing provider parameters

### ISSUE THREAD

**Issue by ArchiFleKs** [particuleio/terraform-scaleway-kapsule#3]
Juste leaving this here for futur update after wednesday. Module is missing some new feature like:
- `project_id` in cluster
- `delete_additionnal_resources` in cluster which is nice to have for the CI
- `kubelet-args` in node pool
- `zone` in node pool

**Comment by rguichard** [comment]
https://github.com/particuleio/terraform-scaleway-kapsule/pull/4

**Comment by ArchiFleKs** [comment]
closed by #4
