### ISSUE TITLE
Support Kapsule with a Private Network

### ISSUE THREAD

**Issue by FlorentPoinsaut** [particuleio/terraform-scaleway-kapsule#45]
Hi!

Thank you for your great work with this module.

Public-only endpoints are deprecated and will reach end of support in Q1/2024.
If I am right, `private_network_id` attribute of `scaleway_k8s_cluster` is missing to do this.

Source:
- https://www.scaleway.com/en/docs/containers/kubernetes/reference-content/secure-cluster-with-private-network/
- https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_cluster

Regards,

**Comment by tsaquet** [comment]
Hello !

I needed this to work tonight, I started the fix (enough to make it work but probably not enough to be clean !) here : 
https://github.com/solution-libre/terraform-scaleway-kapsule/tree/add-vpc-pn

We can discuss this tomorrow :)

**Comment by FlorentPoinsaut** [comment]
Always required. :)
