### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by remyleone** [particuleio/terraform-scaleway-kapsule#7]
When I click on the example > Simple on this page: https://registry.terraform.io/modules/particuleio/kapsule/scaleway/latest
I get a broken link: https://registry.terraform.io/modules/particuleio/kapsule/scaleway/latest/examples/simple

```
This is a submodule used internally by / / . Using this submodule on its own is not recommended.

Submodules without a README or README.md are considered to be internal-only by the Terraform Registry. If this submodule should not be considered internal, add a readme which describes what this submodule is for and how it should be used.

For more information about the expected structure of modules in the Registry, see the Standard Module Structure in the Terraform Registry documentation .
```

**Comment by ArchiFleKs** [comment]
Hi thanks for the info, will fix the link

**Comment by ArchiFleKs** [comment]
The example just does not have a variable.tf, it is a pretty simple example. I added a README with terraform-docs, please feel free to open a PR and add a more complete example.
